name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'LICENCE'
      - 'renovate.json'
      - '**/*.gif'

permissions:
  contents: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Setup JDK 17
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle-Wrapper
        uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1.1.0
      - name: Setup Gradle
        uses: gradle/gradle-build-action@b5126f31dbc19dd434c3269bf8c28c315e121da2 # v2.8.1
        with:
          dependency-graph: generate-and-submit
      - name: Initialize CodeQL
        uses: github/codeql-action/init@6a28655e3dcb49cb0840ea372fd6d17733edd8a4 # v2
        with:
          languages: java
          queries: security-and-quality
      - name: Check
        run: ./gradlew check
      - name: Output Test-Summary
        run: cat ./tournament-core/build/reports/summary.md > $GITHUB_STEP_SUMMARY
        if: success() || failure()
      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@6a28655e3dcb49cb0840ea372fd6d17733edd8a4 # v2
