name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'LICENCE'
      - 'renovate.json'
      - '**/*.gif'

permissions:
  contents: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup JDK 17
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle-Wrapper
        uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1.1.0
      - name: Setup Gradle
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        with:
          dependency-graph: generate-and-submit
      - name: Initialize CodeQL
        uses: github/codeql-action/init@49abf0ba24d0b7953cb586944e918a0b92074c80 # v2
        with:
          languages: java
          queries: security-and-quality
      - name: Check
        run: ./gradlew check
      - name: Output Test-Summary
        run: cat ./tournament-core/build/reports/summary.md > $GITHUB_STEP_SUMMARY
        if: success() || failure()
      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@49abf0ba24d0b7953cb586944e918a0b92074c80 # v2
