name: Build and Test

on: [ pull_request ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle-Wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          dependency-graph: generate-and-submit
      - name: Check
        run: ./gradlew check
