name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'LICENCE'
      - 'renovate.json'
      - '**/*.gif'

permissions:
  contents: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup JDK 21
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Validate Gradle-Wrapper
        uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1.1.0
      - name: Setup Gradle
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa # v2.12.0
        with:
          dependency-graph: generate-and-submit
      - name: Initialize CodeQL
        uses: github/codeql-action/init@8a470fddafa5cbb6266ee11b37ef4d8aae19c571 # v3
        with:
          languages: java
          queries: security-and-quality
      - name: Check
        run: ./gradlew check
      - name: Output Test-Summary
        run: cat ./tournament-core/build/reports/summary.md > $GITHUB_STEP_SUMMARY
        if: success() || failure()
      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@8a470fddafa5cbb6266ee11b37ef4d8aae19c571 # v3
