name: Build & Package for Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle-Wrapper
        uses: gradle/wrapper-validation-action@v1.1.0
      - name: Build & Package
        uses: gradle/gradle-build-action@v2.7.1
        with:
          arguments: packageReleaseMsi
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: package-windows
          path: ${{ github.workspace }}/tournament-desktop/build/compose/binaries/main-release/msi/*.msi
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle-Wrapper
        uses: gradle/wrapper-validation-action@v1.1.0
      - name: Build & Package
        uses: gradle/gradle-build-action@v2.7.1
        with:
          arguments: packageReleaseDeb
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: package-debian
          path: ${{ github.workspace }}/tournament-desktop/build/compose/binaries/main-release/deb/*.deb
  create-release:
    needs: [windows, linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Windows
        uses: actions/download-artifact@v3
        with:
          name: package-windows
      - name: Download Debian
        uses: actions/download-artifact@v3
        with:
          name: package-debian
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.msi
            *.deb
